language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  
env:
  - TESTER_PHP_BIN=php
  
matrix:
  allow_failures:
    - php: hhvm
  
before_install:
  - composer self-update
  
install:
  - composer install --no-interaction --prefer-source
  
script:
  - ./vendor/bin/tester -p $TESTER_PHP_BIN -s -c ./tests/php.ini ./tests
  
after_failure:
  - 'for i in $(find ./tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done'
